export const DOG_BREEDS: string[] = [
  'Mixed / Unknown',
  'Australian Shepherd',
  'Beagle',
  'Bernese Mountain Dog',
  'Bichon Frise',
  'Border Collie',
  'Boston Terrier',
  'Boxer',
  'Brittany',
  'Bulldog',
  'Cavalier King Charles Spaniel',
  'Chihuahua',
  'Cocker Spaniel',
  'Collie',
  'Corgi (Pembroke Welsh)',
  'Dachshund',
  'Dalmatian',
  'Doberman Pinscher',
  'English Springer Spaniel',
  'French Bulldog',
  'German Shepherd',
  'German Shorthaired Pointer',
  'Golden Retriever',
  'Great Dane',
  'Great Pyrenees',
  'Havanese',
  'Husky (Siberian)',
  'Irish Setter',
  'Jack Russell Terrier',
  'Labrador Retriever',
  'Maltese',
  'Miniature Pinscher',
  'Miniature Schnauzer',
  'Newfoundland',
  'Papillon',
  'Pekingese',
  'Pit Bull Terrier',
  'Pomeranian',
  'Poodle (Miniature)',
  'Poodle (Standard)',
  'Poodle (Toy)',
  'Pug',
  'Rottweiler',
  'Saint Bernard',
  'Samoyed',
  'Shiba Inu',
  'Shih Tzu',
  'Vizsla',
  'Weimaraner',
  'West Highland White Terrier',
  'Whippet',
  'Yorkshire Terrier',
];

export const CAT_BREEDS: string[] = [
  'Mixed / Unknown',
  'Abyssinian',
  'American Shorthair',
  'Bengal',
  'Birman',
  'British Shorthair',
  'Burmese',
  'Devon Rex',
  'Exotic Shorthair',
  'Himalayan',
  'Maine Coon',
  'Manx',
  'Norwegian Forest Cat',
  'Oriental Shorthair',
  'Persian',
  'Ragdoll',
  'Russian Blue',
  'Scottish Fold',
  'Siamese',
  'Sphynx',
  'Tonkinese',
  'Turkish Angora',
];

export function getBreedsForType(petType: 'dog' | 'cat'): string[] {
  return petType === 'dog' ? DOG_BREEDS : CAT_BREEDS;
}
