// This file will be auto-generated by running:
// npx supabase gen types typescript --project-id $PROJECT_ID > types/database.ts
//
// For now, this is a placeholder with the expected schema shape.
// Replace this entire file after running the gen command against your live Supabase project.

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[];

export interface Database {
  public: {
    Tables: {
      users: {
        Row: {
          id: string;
          email: string;
          weight_unit: 'kg' | 'lbs';
          created_at: string;
        };
        Insert: {
          id: string;
          email: string;
          weight_unit?: 'kg' | 'lbs';
          created_at?: string;
        };
        Update: {
          id?: string;
          email?: string;
          weight_unit?: 'kg' | 'lbs';
          created_at?: string;
        };
      };
      pets: {
        Row: {
          id: string;
          user_id: string;
          pet_type: 'dog' | 'cat';
          name: string;
          breed: string | null;
          date_of_birth: string | null;
          approximate_age_months: number | null;
          sex: 'male' | 'female' | 'unknown' | null;
          weight: number | null;
          microchip_number: string | null;
          profile_photo_url: string | null;
          is_archived: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          pet_type: 'dog' | 'cat';
          name: string;
          breed?: string | null;
          date_of_birth?: string | null;
          approximate_age_months?: number | null;
          sex?: 'male' | 'female' | 'unknown' | null;
          weight?: number | null;
          microchip_number?: string | null;
          profile_photo_url?: string | null;
          is_archived?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          pet_type?: 'dog' | 'cat';
          name?: string;
          breed?: string | null;
          date_of_birth?: string | null;
          approximate_age_months?: number | null;
          sex?: 'male' | 'female' | 'unknown' | null;
          weight?: number | null;
          microchip_number?: string | null;
          profile_photo_url?: string | null;
          is_archived?: boolean;
          created_at?: string;
          updated_at?: string;
        };
      };
      vet_visits: {
        Row: {
          id: string;
          pet_id: string;
          date: string;
          clinic_name: string | null;
          reason: string | null;
          notes: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          pet_id: string;
          date: string;
          clinic_name?: string | null;
          reason?: string | null;
          notes?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          pet_id?: string;
          date?: string;
          clinic_name?: string | null;
          reason?: string | null;
          notes?: string | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      vet_visit_attachments: {
        Row: {
          id: string;
          vet_visit_id: string;
          file_url: string;
          file_type: 'image' | 'document';
          file_name: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          vet_visit_id: string;
          file_url: string;
          file_type: 'image' | 'document';
          file_name?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          vet_visit_id?: string;
          file_url?: string;
          file_type?: 'image' | 'document';
          file_name?: string | null;
          created_at?: string;
        };
      };
      vaccinations: {
        Row: {
          id: string;
          pet_id: string;
          vaccine_name: string;
          date_administered: string;
          next_due_date: string | null;
          clinic_name: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          pet_id: string;
          vaccine_name: string;
          date_administered: string;
          next_due_date?: string | null;
          clinic_name?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          pet_id?: string;
          vaccine_name?: string;
          date_administered?: string;
          next_due_date?: string | null;
          clinic_name?: string | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      medications: {
        Row: {
          id: string;
          pet_id: string;
          name: string;
          dosage: string | null;
          frequency: string | null;
          start_date: string;
          end_date: string | null;
          prescribing_vet: string | null;
          notes: string | null;
          is_completed: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          pet_id: string;
          name: string;
          dosage?: string | null;
          frequency?: string | null;
          start_date: string;
          end_date?: string | null;
          prescribing_vet?: string | null;
          notes?: string | null;
          is_completed?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          pet_id?: string;
          name?: string;
          dosage?: string | null;
          frequency?: string | null;
          start_date?: string;
          end_date?: string | null;
          prescribing_vet?: string | null;
          notes?: string | null;
          is_completed?: boolean;
          created_at?: string;
          updated_at?: string;
        };
      };
      weight_entries: {
        Row: {
          id: string;
          pet_id: string;
          weight: number;
          date: string;
          note: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          pet_id: string;
          weight: number;
          date: string;
          note?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          pet_id?: string;
          weight?: number;
          date?: string;
          note?: string | null;
          created_at?: string;
        };
      };
      food_entries: {
        Row: {
          id: string;
          pet_id: string;
          brand: string;
          product_name: string | null;
          food_type: 'dry' | 'wet' | 'raw' | 'mixed' | null;
          amount_per_meal: string | null;
          meals_per_day: number | null;
          start_date: string;
          end_date: string | null;
          reason_for_change: string | null;
          notes: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          pet_id: string;
          brand: string;
          product_name?: string | null;
          food_type?: 'dry' | 'wet' | 'raw' | 'mixed' | null;
          amount_per_meal?: string | null;
          meals_per_day?: number | null;
          start_date: string;
          end_date?: string | null;
          reason_for_change?: string | null;
          notes?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          pet_id?: string;
          brand?: string;
          product_name?: string | null;
          food_type?: 'dry' | 'wet' | 'raw' | 'mixed' | null;
          amount_per_meal?: string | null;
          meals_per_day?: number | null;
          start_date?: string;
          end_date?: string | null;
          reason_for_change?: string | null;
          notes?: string | null;
          created_at?: string;
          updated_at?: string;
        };
      };
    };
    Views: Record<string, never>;
    Functions: Record<string, never>;
    Enums: Record<string, never>;
  };
}
