// This file will be auto-generated by running:
// npx supabase gen types typescript --project-id $PROJECT_ID > types/database.ts
//
// For now, this is a placeholder with the expected schema shape.
// Replace this entire file after running the gen command against your live Supabase project.

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[];

export interface Database {
  public: {
    Tables: {
      users: {
        Row: {
          id: string;
          email: string;
          display_name: string | null;
          weight_unit: 'kg' | 'lbs';
          push_tokens: Json;
          reminders_enabled: boolean;
          medication_reminder_time: string;
          vaccination_advance_days: number;
          timezone: string;
          created_at: string;
        };
        Insert: {
          id: string;
          email: string;
          display_name?: string | null;
          weight_unit?: 'kg' | 'lbs';
          push_tokens?: Json;
          reminders_enabled?: boolean;
          medication_reminder_time?: string;
          vaccination_advance_days?: number;
          timezone?: string;
          created_at?: string;
        };
        Update: {
          id?: string;
          email?: string;
          display_name?: string | null;
          weight_unit?: 'kg' | 'lbs';
          push_tokens?: Json;
          reminders_enabled?: boolean;
          medication_reminder_time?: string;
          vaccination_advance_days?: number;
          timezone?: string;
          created_at?: string;
        };
      };
      families: {
        Row: {
          id: string;
          name: string;
          created_by: string;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          name?: string;
          created_by: string;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          name?: string;
          created_by?: string;
          created_at?: string;
          updated_at?: string;
        };
      };
      family_members: {
        Row: {
          id: string;
          family_id: string;
          user_id: string;
          role: 'admin' | 'member';
          joined_at: string;
        };
        Insert: {
          id?: string;
          family_id: string;
          user_id: string;
          role: 'admin' | 'member';
          joined_at?: string;
        };
        Update: {
          id?: string;
          family_id?: string;
          user_id?: string;
          role?: 'admin' | 'member';
          joined_at?: string;
        };
      };
      family_invites: {
        Row: {
          id: string;
          family_id: string;
          invite_code: string;
          invited_by: string;
          expires_at: string;
          accepted_by: string | null;
          accepted_at: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          family_id: string;
          invite_code: string;
          invited_by: string;
          expires_at: string;
          accepted_by?: string | null;
          accepted_at?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          family_id?: string;
          invite_code?: string;
          invited_by?: string;
          expires_at?: string;
          accepted_by?: string | null;
          accepted_at?: string | null;
          created_at?: string;
        };
      };
      pets: {
        Row: {
          id: string;
          family_id: string;
          created_by: string | null;
          pet_type: 'dog' | 'cat';
          name: string;
          breed: string | null;
          date_of_birth: string | null;
          approximate_age_months: number | null;
          sex: 'male' | 'female' | 'unknown' | null;
          weight: number | null;
          microchip_number: string | null;
          profile_photo_url: string | null;
          is_archived: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          family_id: string;
          created_by?: string | null;
          pet_type: 'dog' | 'cat';
          name: string;
          breed?: string | null;
          date_of_birth?: string | null;
          approximate_age_months?: number | null;
          sex?: 'male' | 'female' | 'unknown' | null;
          weight?: number | null;
          microchip_number?: string | null;
          profile_photo_url?: string | null;
          is_archived?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          family_id?: string;
          created_by?: string | null;
          pet_type?: 'dog' | 'cat';
          name?: string;
          breed?: string | null;
          date_of_birth?: string | null;
          approximate_age_months?: number | null;
          sex?: 'male' | 'female' | 'unknown' | null;
          weight?: number | null;
          microchip_number?: string | null;
          profile_photo_url?: string | null;
          is_archived?: boolean;
          created_at?: string;
          updated_at?: string;
        };
      };
      vet_visits: {
        Row: {
          id: string;
          pet_id: string;
          date: string;
          clinic_name: string | null;
          reason: string | null;
          notes: string | null;
          created_by: string | null;
          modified_by: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          pet_id: string;
          date: string;
          clinic_name?: string | null;
          reason?: string | null;
          notes?: string | null;
          created_by?: string | null;
          modified_by?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          pet_id?: string;
          date?: string;
          clinic_name?: string | null;
          reason?: string | null;
          notes?: string | null;
          created_by?: string | null;
          modified_by?: string | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      vet_visit_attachments: {
        Row: {
          id: string;
          vet_visit_id: string;
          file_url: string;
          file_type: 'image' | 'document';
          file_name: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          vet_visit_id: string;
          file_url: string;
          file_type: 'image' | 'document';
          file_name?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          vet_visit_id?: string;
          file_url?: string;
          file_type?: 'image' | 'document';
          file_name?: string | null;
          created_at?: string;
        };
      };
      vaccinations: {
        Row: {
          id: string;
          pet_id: string;
          vaccine_name: string;
          date_administered: string;
          next_due_date: string | null;
          clinic_name: string | null;
          created_by: string | null;
          modified_by: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          pet_id: string;
          vaccine_name: string;
          date_administered: string;
          next_due_date?: string | null;
          clinic_name?: string | null;
          created_by?: string | null;
          modified_by?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          pet_id?: string;
          vaccine_name?: string;
          date_administered?: string;
          next_due_date?: string | null;
          clinic_name?: string | null;
          created_by?: string | null;
          modified_by?: string | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      medications: {
        Row: {
          id: string;
          pet_id: string;
          name: string;
          dosage: string | null;
          frequency: string | null;
          start_date: string;
          end_date: string | null;
          prescribing_vet: string | null;
          notes: string | null;
          is_archived: boolean;
          archived_at: string | null;
          created_by: string | null;
          modified_by: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          pet_id: string;
          name: string;
          dosage?: string | null;
          frequency?: string | null;
          start_date: string;
          end_date?: string | null;
          prescribing_vet?: string | null;
          notes?: string | null;
          is_archived?: boolean;
          archived_at?: string | null;
          created_by?: string | null;
          modified_by?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          pet_id?: string;
          name?: string;
          dosage?: string | null;
          frequency?: string | null;
          start_date?: string;
          end_date?: string | null;
          prescribing_vet?: string | null;
          notes?: string | null;
          is_archived?: boolean;
          archived_at?: string | null;
          created_by?: string | null;
          modified_by?: string | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      medication_doses: {
        Row: {
          id: string;
          medication_id: string;
          given_at: string;
          notes: string | null;
          created_by: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          medication_id: string;
          given_at?: string;
          notes?: string | null;
          created_by?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          medication_id?: string;
          given_at?: string;
          notes?: string | null;
          created_by?: string | null;
          created_at?: string;
        };
      };
      weight_entries: {
        Row: {
          id: string;
          pet_id: string;
          weight: number;
          date: string;
          note: string | null;
          created_by: string | null;
          modified_by: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          pet_id: string;
          weight: number;
          date: string;
          note?: string | null;
          created_by?: string | null;
          modified_by?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          pet_id?: string;
          weight?: number;
          date?: string;
          note?: string | null;
          created_by?: string | null;
          modified_by?: string | null;
          created_at?: string;
        };
      };
      food_entries: {
        Row: {
          id: string;
          pet_id: string;
          brand: string;
          product_name: string | null;
          food_type: 'dry' | 'wet' | 'raw' | 'mixed' | null;
          amount_per_meal: string | null;
          meals_per_day: number | null;
          start_date: string;
          end_date: string | null;
          reason_for_change: string | null;
          notes: string | null;
          created_by: string | null;
          modified_by: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          pet_id: string;
          brand: string;
          product_name?: string | null;
          food_type?: 'dry' | 'wet' | 'raw' | 'mixed' | null;
          amount_per_meal?: string | null;
          meals_per_day?: number | null;
          start_date: string;
          end_date?: string | null;
          reason_for_change?: string | null;
          notes?: string | null;
          created_by?: string | null;
          modified_by?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          pet_id?: string;
          brand?: string;
          product_name?: string | null;
          food_type?: 'dry' | 'wet' | 'raw' | 'mixed' | null;
          amount_per_meal?: string | null;
          meals_per_day?: number | null;
          start_date?: string;
          end_date?: string | null;
          reason_for_change?: string | null;
          notes?: string | null;
          created_by?: string | null;
          modified_by?: string | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      feedback: {
        Row: {
          id: string;
          user_id: string | null;
          user_email: string | null;
          category: 'bug' | 'idea' | null;
          description: string;
          app_version: string | null;
          device_model: string | null;
          os_name: string | null;
          os_version: string | null;
          screen_name: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          user_id?: string | null;
          user_email?: string | null;
          category?: 'bug' | 'idea' | null;
          description: string;
          app_version?: string | null;
          device_model?: string | null;
          os_name?: string | null;
          os_version?: string | null;
          screen_name?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string | null;
          user_email?: string | null;
          category?: 'bug' | 'idea' | null;
          description?: string;
          app_version?: string | null;
          device_model?: string | null;
          os_name?: string | null;
          os_version?: string | null;
          screen_name?: string | null;
          created_at?: string;
        };
      };
      notification_log: {
        Row: {
          id: string;
          user_id: string;
          notification_type: string;
          reference_id: string;
          reminder_key: string;
          sent_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          notification_type: string;
          reference_id: string;
          reminder_key: string;
          sent_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          notification_type?: string;
          reference_id?: string;
          reminder_key?: string;
          sent_at?: string;
        };
      };
    };
    Views: Record<string, never>;
    Functions: {
      accept_invite: {
        Args: { invite_code: string };
        Returns: void;
      };
      leave_family: {
        Args: Record<string, never>;
        Returns: void;
      };
    };
    Enums: Record<string, never>;
  };
}
